version: 2.1
orbs:
  ruby-rails: sul-dlss/ruby-rails@4.0.0
workflows:
  build:
    jobs:
      - ruby-rails/lint:
          name: lint
          executor:
            name: ruby-rails/ruby
            ruby-tag: '3.2.2'
